---
apt_packages:
  - libpq-dev
  - mc
  - vim
  - ruby2.5-dev
  - g++

ruby_version: 2.5

postgresql_databases:
  - name: shakuro
    owner: user_shakuro
  - name: shakuro_test
    owner: user_shakuro

postgresql_users:
  - name: user_shakuro
    pass: 123456

postgresql_user_privileges:
  - name: user_shakuro
    db: shakuro
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
  - name: user_shakuro
    db: shakuro_test
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
